Added support for saving multiple aggregates at once
tacta-io/Tacta.EventStore pull request #19
Opened 2024-01-29 11:03 UTC by SegoMarko

Added support for saving multiple aggregates at once. Multiple aggregates of different types or same type can be saved at once within a transaction. If implicit transaction doesn't exist it will be created. Another route to implement this would be to skip creating implicit transaction and instead implement new functionality in [Tacta.Connection](https://github.com/tacta-io/Tacta.Connection) project to support  creating a transaction if one isn't provided from Tacta.Connection.ITransactionStore.

2024-01-29 11:23 UTC, bolicd approved these changes
This seems fine. Code is clear and readable. transaction isolation level is ok.

2024-02-12 08:54 UTC, jasminmemisevictacta requested changes

2024-02-12 08:54 UTC, jasminmemisevictacta commented on Tacta.EventStore/Repository/EventStoreRepository.cs
> -                Payload = JsonConvert.SerializeObject(eventRecord.Event, Formatting.Indented, _jsonSerializerSettings),
now our _jsonSerializerSettings is unused field.

2024-04-10 11:25 UTC, rmares approved these changes

2024-05-28 07:30 UTC, jasminmemisevictacta approved these changes

2024-05-29 10:16 UTC, merged